version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://${HOST_IP:-localhost}:3001
    depends_on:
      - jsonserver
    networks:
      - app-network

  jsonserver:
    build:
      context: .
      dockerfile: Dockerfile.jsonserver
    ports:
      - "3001:3001"
    volumes:
      - ./db.json:/app/db.json
    command: json-server --watch /app/db.json --host 0.0.0.0 --port 3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge