FROM node:18-alpine

WORKDIR /app

RUN npm install -g json-server

COPY db.json .
RUN chmod 777 /app/db.json

EXPOSE 3001

CMD ["json-server", "--host", "0.0.0.0", "--watch", "db.json", "--port", "3001"]